/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alphacare;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author kken1
 */
public class AdminPanel extends javax.swing.JPanel {

    private Administrator admin;
    /**
     * Creates new form AdminPanel
     */
    public AdminPanel(Administrator theAdmin) {
        
        initComponents();
        admin = theAdmin;
        setNameText();
        this.NewUserPanel.setVisible(false);
    }
    
    private void setNameText(){
        
        this.getNameLabel().setText("Welcome, " + this.getAdmin().getFullName());
        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        optionsLabel = new javax.swing.JLabel();
        systemStatusButton = new javax.swing.JButton();
        appPerformanceButton = new javax.swing.JButton();
        totalUsersButton = new javax.swing.JButton();
        addNewUserButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        NewUserPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PasswordText = new javax.swing.JTextField();
        UserNameText = new javax.swing.JTextField();
        FirstNameText = new javax.swing.JTextField();
        LastNameText = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jPanel1.setBackground(new java.awt.Color(230, 39, 57));
        jPanel1.setPreferredSize(new java.awt.Dimension(525, 470));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Admin's name");

        optionsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        optionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        optionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        optionsLabel.setText("Choose one:");

        systemStatusButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        systemStatusButton.setText("System Status");
        systemStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemStatusButtonActionPerformed(evt);
            }
        });

        appPerformanceButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        appPerformanceButton.setText("App Performance");
        appPerformanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appPerformanceButtonActionPerformed(evt);
            }
        });

        totalUsersButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalUsersButton.setText("Total Users");
        totalUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalUsersButtonActionPerformed(evt);
            }
        });

        addNewUserButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addNewUserButton.setText("New Patient");
        addNewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewUserButtonActionPerformed(evt);
            }
        });

        LogOutButton.setText("Logout");

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("User Name:");

        jLabel5.setText("Password:");

        PasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextActionPerformed(evt);
            }
        });

        UserNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextActionPerformed(evt);
            }
        });

        FirstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextActionPerformed(evt);
            }
        });

        LastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");

        javax.swing.GroupLayout NewUserPanelLayout = new javax.swing.GroupLayout(NewUserPanel);
        NewUserPanel.setLayout(NewUserPanelLayout);
        NewUserPanelLayout.setHorizontalGroup(
            NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewUserPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewUserPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LastNameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NewUserPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SaveButton)
                            .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UserNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        NewUserPanelLayout.setVerticalGroup(
            NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewUserPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LastNameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(NewUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaveButton)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addNewUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(appPerformanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(systemStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(LogOutButton)))
                        .addGap(95, 95, 95))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(optionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NewUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LogOutButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(optionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addNewUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appPerformanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(systemStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(NewUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewUserButtonActionPerformed

    private void totalUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalUsersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalUsersButtonActionPerformed

    private void appPerformanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appPerformanceButtonActionPerformed

        DefaultCategoryDataset performanceData = new DefaultCategoryDataset();

        performanceData.setValue(78.80, "Andrew", "Gordan");
        performanceData.setValue(68.80, "Ben", "Carson");
        performanceData.setValue(38.80, "Robin", "Williams");
        performanceData.setValue(18.80, "Joe", "Snow");
        performanceData.setValue(28.80, "Kon Woo", "Kim");
        performanceData.setValue(98.80, "David", "David");

        JFreeChart performanceChart = ChartFactory.createBarChart("App Performance", "User Name", "Number of Visit", performanceData, PlotOrientation.VERTICAL, true, true, false);

        CategoryPlot performancePlot = performanceChart.getCategoryPlot();
        performancePlot.setRangeGridlinePaint(Color.black);

        ChartFrame frame = new ChartFrame("App Performance", performanceChart, true);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        frame.setSize(800, 600);

    }//GEN-LAST:event_appPerformanceButtonActionPerformed

    private void systemStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemStatusButtonActionPerformed

        JFrame frame;
        JButton button;

        frame = new JFrame("System Status");

        JLabel status = new JLabel("System Status");
        status.setFont(status.getFont().deriveFont(24.0f));
        status.setBounds(70, 20, 200, 30);

        JLabel current = new JLabel("All systems are operating normally.");
        current.setBounds(50, 70, 200, 30);

        button = new JButton("OK");
        button.setBounds(190,120,100,30);
        button.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {

                frame.dispose();

            }
        });

        frame.add(status);
        frame.add(current);
        frame.add(button);

        frame.setSize(320, 200);
        frame.setLayout(null);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

    }//GEN-LAST:event_systemStatusButtonActionPerformed

    private void PasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextActionPerformed

    private void UserNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTextActionPerformed

    private void FirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextActionPerformed

    private void LastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstNameText;
    private javax.swing.JTextField LastNameText;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JPanel NewUserPanel;
    private javax.swing.JTextField PasswordText;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField UserNameText;
    private javax.swing.JButton addNewUserButton;
    private javax.swing.JButton appPerformanceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel optionsLabel;
    private javax.swing.JButton systemStatusButton;
    private javax.swing.JButton totalUsersButton;
    // End of variables declaration//GEN-END:variables

    public Administrator getAdmin() {
        return admin;
    }

    public void setAdmin(Administrator admin) {
        this.admin = admin;
    }

    public JButton getLogOutButton() {
        return LogOutButton;
    }

    public void setLogOutButton(JButton LogOutButton) {
        this.LogOutButton = LogOutButton;
    }

    public JButton getAddNewUserButton() {
        return addNewUserButton;
    }

    public void setAddNewUserButton(JButton addNewUserButton) {
        this.addNewUserButton = addNewUserButton;
    }

    public JButton getAppPerformanceButton() {
        return appPerformanceButton;
    }

    public void setAppPerformanceButton(JButton appPerformanceButton) {
        this.appPerformanceButton = appPerformanceButton;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getNameLabel() {
        return nameLabel;
    }

    public void setNameLabel(JLabel nameLabel) {
        this.nameLabel = nameLabel;
    }

    public JLabel getOptionsLabel() {
        return optionsLabel;
    }

    public void setOptionsLabel(JLabel optionsLabel) {
        this.optionsLabel = optionsLabel;
    }

    public JButton getSystemStatusButton() {
        return systemStatusButton;
    }

    public void setSystemStatusButton(JButton systemStatusButton) {
        this.systemStatusButton = systemStatusButton;
    }

    public JButton getTotalUsersButton() {
        return totalUsersButton;
    }

    public void setTotalUsersButton(JButton totalUsersButton) {
        this.totalUsersButton = totalUsersButton;
    }

    /**
     * @return the NewUserPanel
     */
    public javax.swing.JPanel getNewUserPanel() {
        return NewUserPanel;
    }

    /**
     * @return the TextFirstName
     */
    public javax.swing.JTextField getTextFirstName() {
        return getPasswordText();
    }

    /**
     * @param TextFirstName the TextFirstName to set
     */
    public void setTextFirstName(javax.swing.JTextField TextFirstName) {
        this.setPasswordText(TextFirstName);
    }

    /**
     * @return the TextFirstName1
     */
    public javax.swing.JTextField getTextFirstName1() {
        return getUserNameText();
    }

    /**
     * @param TextFirstName1 the TextFirstName1 to set
     */
    public void setTextFirstName1(javax.swing.JTextField TextFirstName1) {
        this.setUserNameText(TextFirstName1);
    }

    /**
     * @return the TextFirstName2
     */
    public javax.swing.JTextField getTextFirstName2() {
        return getFirstNameText();
    }

    /**
     * @param TextFirstName2 the TextFirstName2 to set
     */
    public void setTextFirstName2(javax.swing.JTextField TextFirstName2) {
        this.setFirstNameText(TextFirstName2);
    }

    /**
     * @return the TextFirstName3
     */
    public javax.swing.JTextField getTextFirstName3() {
        return getLastNameText();
    }

    /**
     * @param TextFirstName3 the TextFirstName3 to set
     */
    public void setTextFirstName3(javax.swing.JTextField TextFirstName3) {
        this.setLastNameText(TextFirstName3);
    }

    /**
     * @return the FirstNameText
     */
    public javax.swing.JTextField getFirstNameText() {
        return FirstNameText;
    }

    /**
     * @param FirstNameText the FirstNameText to set
     */
    public void setFirstNameText(javax.swing.JTextField FirstNameText) {
        this.FirstNameText = FirstNameText;
    }

    /**
     * @return the LastNameText
     */
    public javax.swing.JTextField getLastNameText() {
        return LastNameText;
    }

    /**
     * @param LastNameText the LastNameText to set
     */
    public void setLastNameText(javax.swing.JTextField LastNameText) {
        this.LastNameText = LastNameText;
    }

    /**
     * @param NewUserPanel the NewUserPanel to set
     */
    public void setNewUserPanel(javax.swing.JPanel NewUserPanel) {
        this.NewUserPanel = NewUserPanel;
    }

    /**
     * @return the PasswordText
     */
    public javax.swing.JTextField getPasswordText() {
        return PasswordText;
    }

    /**
     * @param PasswordText the PasswordText to set
     */
    public void setPasswordText(javax.swing.JTextField PasswordText) {
        this.PasswordText = PasswordText;
    }

    /**
     * @return the SaveButton
     */
    public javax.swing.JButton getSaveButton() {
        return SaveButton;
    }

    /**
     * @param SaveButton the SaveButton to set
     */
    public void setSaveButton(javax.swing.JButton SaveButton) {
        this.SaveButton = SaveButton;
    }

    /**
     * @return the UserNameText
     */
    public javax.swing.JTextField getUserNameText() {
        return UserNameText;
    }

    /**
     * @param UserNameText the UserNameText to set
     */
    public void setUserNameText(javax.swing.JTextField UserNameText) {
        this.UserNameText = UserNameText;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @param jLabel4 the jLabel4 to set
     */
    public void setjLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @param jLabel5 the jLabel5 to set
     */
    public void setjLabel5(javax.swing.JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    

}
