/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alphacare;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author kken1
 */
public class AdminPanel extends javax.swing.JPanel {

    private Administrator admin;
    /**
     * Creates new form AdminPanel
     */
    public AdminPanel(Administrator theAdmin) {
        
        initComponents();
        admin = theAdmin;
        setNameText();
        
    }
    
    private void setNameText(){
        
        this.getNameLabel().setText("Welcome, " + this.admin.getFullName());
        
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        optionsLabel = new javax.swing.JLabel();
        systemStatusButton = new javax.swing.JButton();
        appPerformanceButton = new javax.swing.JButton();
        totalUsersButton = new javax.swing.JButton();
        addNewUserButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(230, 39, 57));
        jPanel1.setPreferredSize(new java.awt.Dimension(525, 470));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Admin's name");

        optionsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        optionsLabel.setForeground(new java.awt.Color(255, 255, 255));
        optionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        optionsLabel.setText("Choose one:");

        systemStatusButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        systemStatusButton.setText("System Status");
        systemStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemStatusButtonActionPerformed(evt);
            }
        });

        appPerformanceButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        appPerformanceButton.setText("App Performance");
        appPerformanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appPerformanceButtonActionPerformed(evt);
            }
        });

        totalUsersButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalUsersButton.setText("Total Users");
        totalUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalUsersButtonActionPerformed(evt);
            }
        });

        addNewUserButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addNewUserButton.setText("Add New User");
        addNewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewUserButtonActionPerformed(evt);
            }
        });

        LogOutButton.setText("Logout");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addNewUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(appPerformanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(systemStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LogOutButton)
                        .addGap(95, 95, 95))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(optionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LogOutButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(optionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addNewUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(appPerformanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(systemStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewUserButtonActionPerformed

    private void totalUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalUsersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalUsersButtonActionPerformed

    private void appPerformanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appPerformanceButtonActionPerformed

        DefaultCategoryDataset performanceData = new DefaultCategoryDataset();

        performanceData.setValue(78.80, "Andrew", "Gordan");
        performanceData.setValue(68.80, "Ben", "Carson");
        performanceData.setValue(38.80, "Robin", "Williams");
        performanceData.setValue(18.80, "Joe", "Snow");
        performanceData.setValue(28.80, "Kon Woo", "Kim");
        performanceData.setValue(98.80, "David", "David");

        JFreeChart performanceChart = ChartFactory.createBarChart("App Performance", "User Name", "Number of Visit", performanceData, PlotOrientation.VERTICAL, true, true, false);

        CategoryPlot performancePlot = performanceChart.getCategoryPlot();
        performancePlot.setRangeGridlinePaint(Color.black);

        ChartFrame frame = new ChartFrame("App Performance", performanceChart, true);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        frame.setSize(800, 600);

    }//GEN-LAST:event_appPerformanceButtonActionPerformed

    private void systemStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemStatusButtonActionPerformed

        JFrame frame;
        JButton button;

        frame = new JFrame("System Status");

        JLabel status = new JLabel("System Status");
        status.setFont(status.getFont().deriveFont(24.0f));
        status.setBounds(70, 20, 200, 30);

        JLabel current = new JLabel("All systems are operating normally.");
        current.setBounds(50, 70, 200, 30);

        button = new JButton("OK");
        button.setBounds(190,120,100,30);
        button.addActionListener(new ActionListener(){

            public void actionPerformed(ActionEvent e) {

                frame.dispose();

            }
        });

        frame.add(status);
        frame.add(current);
        frame.add(button);

        frame.setSize(320, 200);
        frame.setLayout(null);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

    }//GEN-LAST:event_systemStatusButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton addNewUserButton;
    private javax.swing.JButton appPerformanceButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel optionsLabel;
    private javax.swing.JButton systemStatusButton;
    private javax.swing.JButton totalUsersButton;
    // End of variables declaration//GEN-END:variables

    public Administrator getAdmin() {
        return admin;
    }

    public void setAdmin(Administrator admin) {
        this.admin = admin;
    }

    public JButton getLogOutButton() {
        return LogOutButton;
    }

    public void setLogOutButton(JButton LogOutButton) {
        this.LogOutButton = LogOutButton;
    }

    public JButton getAddNewUserButton() {
        return addNewUserButton;
    }

    public void setAddNewUserButton(JButton addNewUserButton) {
        this.addNewUserButton = addNewUserButton;
    }

    public JButton getAppPerformanceButton() {
        return appPerformanceButton;
    }

    public void setAppPerformanceButton(JButton appPerformanceButton) {
        this.appPerformanceButton = appPerformanceButton;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getNameLabel() {
        return nameLabel;
    }

    public void setNameLabel(JLabel nameLabel) {
        this.nameLabel = nameLabel;
    }

    public JLabel getOptionsLabel() {
        return optionsLabel;
    }

    public void setOptionsLabel(JLabel optionsLabel) {
        this.optionsLabel = optionsLabel;
    }

    public JButton getSystemStatusButton() {
        return systemStatusButton;
    }

    public void setSystemStatusButton(JButton systemStatusButton) {
        this.systemStatusButton = systemStatusButton;
    }

    public JButton getTotalUsersButton() {
        return totalUsersButton;
    }

    public void setTotalUsersButton(JButton totalUsersButton) {
        this.totalUsersButton = totalUsersButton;
    }

    

}
